name: Guix Build CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  guix-build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Install Guix
      run: |
        wget https://git.savannah.gnu.org/cgit/guix.git/plain/etc/guix-install.sh
        chmod +x guix-install.sh
        sudo ./guix-install.sh
        
    - name: Setup Guix environment
      run: |
        export PATH="/var/guix/profiles/per-user/$USER/current-guix/bin:$PATH"
        guix pull
        
    - name: Build with Guix
      run: |
        export PATH="/var/guix/profiles/per-user/$USER/current-guix/bin:$PATH"
        guix build -f packaging/opencog.scm