name: Guix Build CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  guix-build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install GNU Guix non-interactively (SSR safe)
        run: |
          # Download the Guix install script to a temp file
          curl -fsSL https://git.savannah.gnu.org/cgit/guix.git/plain/etc/guix-install.sh -o /tmp/guix-install.sh
          # Execute the script as root, non-interactively
          printf '\n' | sudo bash /tmp/guix-install.sh

      - name: Setup Guix environment
        run: |
          # Use $(whoami) for reliable user detection instead of $USER
          export PATH="/var/guix/profiles/per-user/$(whoami)/current-guix/bin:$PATH"
          # Start the guix daemon
          sudo systemctl start guix-daemon || \
            sudo /var/guix/profiles/per-user/root/current-guix/bin/guix-daemon \
            --build-users-group=guixbuild &
          # Update guix
          guix pull --verbosity=1

      - name: Build with Guix
        run: |
          # Use $(whoami) for consistent PATH construction
          export PATH="/var/guix/profiles/per-user/$(whoami)/current-guix/bin:$PATH"
          # Ensure guix daemon is accessible
          guix describe
          # Build the package
          guix build -f guix.scm --verbosity=1
